title: WAHS Robotics Club Information
description: Info about the WAHS Robotics Team sponsorship options
author: "WAHS Robotics"

remote_theme: jekyll/minima

base_url: /sponsorship-info
repository: WAHS-Robotics-Club/sponsorship-info

# Minima social links
github_username: WAHS-Robotics-Club
rss: false

google_analytics: y

show_excerpts: false

minima:
  date_format: "%Y-%m-%d"
  skin: solarized-light

# Minima: custom header links
header_pages:
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
